### ISSUE TITLE
Exception encountered during context initialization

### ISSUE THREAD

**Issue by Xhings** [strepsirrhini-army/chaos-lemur#11]
Hi I am pushing the code to PCF dev instance at https://console.run.pivotal.io in my org but getting below exception:

[exception.txt](https://github.com/strepsirrhini-army/chaos-lemur/files/1587913/exception.txt)

**Comment by nebhale** [comment]
The problem is that you’ve not [configured a director](https://github.com/strepsirrhini-army/chaos-lemur/blob/master/src/main/java/io/pivotal/strepsirrhini/chaoslemur/infrastructure/StandardDirectorUtils.java#L47).  Please take a look at the [documentation](https://github.com/strepsirrhini-army/chaos-lemur#infrastructure) and ensure that you’ve configured everything that is required.
